version: "2"
services:
  mlserver:
    image: mlserver:latest
    ports:
      - "5000:5000"
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb://mongodb:27017/
    links:
      - mongodb
  
  mongodb:
    image: mongo:4.0.10-xenial
    ports:
      - "27017:27017"